[base]
# 最大启用线程数量
go_max_procs=0
# 模式
mode="dev"

[logger]
# 日志格式
format="text"
# 日志等级
level="debug"

[service]
# 监听地址
host=":8080"
# PPROF 启用
pprof_enabled = true

[discovery]
# 启用静态服务发现
enable_static = true
enable_consul = false
# 静态服务地址
static_services = [
    "otherservice 127.0.0.1:9091 127.0.0.1:9092"
]

[hystrix]
# 上报地址
#statsd_url="${kv_of_consul,openapi/statsd/url}"
timeout=10000
max_concurrent_request=200
error_percent_threshold=20

[invoker]
# 启用调用追踪
tracing_enabled = true
# 启用熔断
hytrix_enabled = true
# 打印日志
do_logger = true

[mysql]
url= "root:lw123456@tcp(120.76.47.222:3306)/server_test"

[application]

# 自定义配置放在这里