// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package userpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type QueryDirect int32

const (
	QueryDirect_QueryDirect_NA QueryDirect = 0
	QueryDirect_NEXT           QueryDirect = 1
	QueryDirect_PREV           QueryDirect = 2
)

var QueryDirect_name = map[int32]string{
	0: "QueryDirect_NA",
	1: "NEXT",
	2: "PREV",
}
var QueryDirect_value = map[string]int32{
	"QueryDirect_NA": 0,
	"NEXT":           1,
	"PREV":           2,
}

func (x QueryDirect) String() string {
	return proto.EnumName(QueryDirect_name, int32(x))
}
func (QueryDirect) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_user_903e6a03efad49bc, []int{0}
}

type CreateUserRequest struct {
	UserName             string   `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password"`
	Mobile               string   `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email"`
	Birthday             string   `protobuf:"bytes,5,opt,name=birthday,proto3" json:"birthday"`
	Address              string   `protobuf:"bytes,6,opt,name=address,proto3" json:"address"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_903e6a03efad49bc, []int{0}
}
func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (dst *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(dst, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateUserRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

func (m *CreateUserRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type CreateUserResponse struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_903e6a03efad49bc, []int{1}
}
func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (dst *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(dst, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type UpdateUserRequest struct {
	UserName             string   `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName"`
	Mobile               string   `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email"`
	Birthday             string   `protobuf:"bytes,5,opt,name=birthday,proto3" json:"birthday"`
	Address              string   `protobuf:"bytes,6,opt,name=address,proto3" json:"address"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_903e6a03efad49bc, []int{2}
}
func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(dst, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UpdateUserRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *UpdateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdateUserRequest) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

func (m *UpdateUserRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type UpdateUserResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_903e6a03efad49bc, []int{3}
}
func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(dst, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

type QueryUserRequest struct {
	UserName             string   `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryUserRequest) Reset()         { *m = QueryUserRequest{} }
func (m *QueryUserRequest) String() string { return proto.CompactTextString(m) }
func (*QueryUserRequest) ProtoMessage()    {}
func (*QueryUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_903e6a03efad49bc, []int{4}
}
func (m *QueryUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryUserRequest.Unmarshal(m, b)
}
func (m *QueryUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryUserRequest.Marshal(b, m, deterministic)
}
func (dst *QueryUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUserRequest.Merge(dst, src)
}
func (m *QueryUserRequest) XXX_Size() int {
	return xxx_messageInfo_QueryUserRequest.Size(m)
}
func (m *QueryUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUserRequest proto.InternalMessageInfo

func (m *QueryUserRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type QueryUserResponse struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId"`
	UserName             string   `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName"`
	Mobile               string   `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email"`
	Birthday             string   `protobuf:"bytes,5,opt,name=birthday,proto3" json:"birthday"`
	Address              string   `protobuf:"bytes,6,opt,name=address,proto3" json:"address"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryUserResponse) Reset()         { *m = QueryUserResponse{} }
func (m *QueryUserResponse) String() string { return proto.CompactTextString(m) }
func (*QueryUserResponse) ProtoMessage()    {}
func (*QueryUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_903e6a03efad49bc, []int{5}
}
func (m *QueryUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryUserResponse.Unmarshal(m, b)
}
func (m *QueryUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryUserResponse.Marshal(b, m, deterministic)
}
func (dst *QueryUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUserResponse.Merge(dst, src)
}
func (m *QueryUserResponse) XXX_Size() int {
	return xxx_messageInfo_QueryUserResponse.Size(m)
}
func (m *QueryUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUserResponse proto.InternalMessageInfo

func (m *QueryUserResponse) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *QueryUserResponse) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *QueryUserResponse) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *QueryUserResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *QueryUserResponse) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

func (m *QueryUserResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type UserListItem struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId"`
	UserName             string   `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName"`
	Mobile               string   `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email"`
	Birthday             string   `protobuf:"bytes,5,opt,name=birthday,proto3" json:"birthday"`
	Address              string   `protobuf:"bytes,6,opt,name=address,proto3" json:"address"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserListItem) Reset()         { *m = UserListItem{} }
func (m *UserListItem) String() string { return proto.CompactTextString(m) }
func (*UserListItem) ProtoMessage()    {}
func (*UserListItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_903e6a03efad49bc, []int{6}
}
func (m *UserListItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListItem.Unmarshal(m, b)
}
func (m *UserListItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListItem.Marshal(b, m, deterministic)
}
func (dst *UserListItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListItem.Merge(dst, src)
}
func (m *UserListItem) XXX_Size() int {
	return xxx_messageInfo_UserListItem.Size(m)
}
func (m *UserListItem) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListItem.DiscardUnknown(m)
}

var xxx_messageInfo_UserListItem proto.InternalMessageInfo

func (m *UserListItem) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserListItem) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserListItem) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *UserListItem) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserListItem) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

func (m *UserListItem) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type QueryUserListRequest struct {
	CreateTime           int64    `protobuf:"varint,1,opt,name=createTime,proto3" json:"createTime"`
	Direct               string   `protobuf:"bytes,2,opt,name=direct,proto3" json:"direct"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryUserListRequest) Reset()         { *m = QueryUserListRequest{} }
func (m *QueryUserListRequest) String() string { return proto.CompactTextString(m) }
func (*QueryUserListRequest) ProtoMessage()    {}
func (*QueryUserListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_903e6a03efad49bc, []int{7}
}
func (m *QueryUserListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryUserListRequest.Unmarshal(m, b)
}
func (m *QueryUserListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryUserListRequest.Marshal(b, m, deterministic)
}
func (dst *QueryUserListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUserListRequest.Merge(dst, src)
}
func (m *QueryUserListRequest) XXX_Size() int {
	return xxx_messageInfo_QueryUserListRequest.Size(m)
}
func (m *QueryUserListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUserListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUserListRequest proto.InternalMessageInfo

func (m *QueryUserListRequest) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *QueryUserListRequest) GetDirect() string {
	if m != nil {
		return m.Direct
	}
	return ""
}

func (m *QueryUserListRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type QueryUserListResponse struct {
	Users                []*UserListItem `protobuf:"bytes,1,rep,name=users,proto3" json:"users"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *QueryUserListResponse) Reset()         { *m = QueryUserListResponse{} }
func (m *QueryUserListResponse) String() string { return proto.CompactTextString(m) }
func (*QueryUserListResponse) ProtoMessage()    {}
func (*QueryUserListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_903e6a03efad49bc, []int{8}
}
func (m *QueryUserListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryUserListResponse.Unmarshal(m, b)
}
func (m *QueryUserListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryUserListResponse.Marshal(b, m, deterministic)
}
func (dst *QueryUserListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUserListResponse.Merge(dst, src)
}
func (m *QueryUserListResponse) XXX_Size() int {
	return xxx_messageInfo_QueryUserListResponse.Size(m)
}
func (m *QueryUserListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUserListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUserListResponse proto.InternalMessageInfo

func (m *QueryUserListResponse) GetUsers() []*UserListItem {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateUserRequest)(nil), "userpb.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "userpb.CreateUserResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "userpb.UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "userpb.UpdateUserResponse")
	proto.RegisterType((*QueryUserRequest)(nil), "userpb.QueryUserRequest")
	proto.RegisterType((*QueryUserResponse)(nil), "userpb.QueryUserResponse")
	proto.RegisterType((*UserListItem)(nil), "userpb.UserListItem")
	proto.RegisterType((*QueryUserListRequest)(nil), "userpb.QueryUserListRequest")
	proto.RegisterType((*QueryUserListResponse)(nil), "userpb.QueryUserListResponse")
	proto.RegisterEnum("userpb.QueryDirect", QueryDirect_name, QueryDirect_value)
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_user_903e6a03efad49bc) }

var fileDescriptor_user_903e6a03efad49bc = []byte{
	// 361 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x94, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0x80, 0xcd, 0xba, 0xd6, 0xf9, 0x26, 0xd2, 0x85, 0x2a, 0xc1, 0x83, 0x8c, 0x9e, 0xc6, 0x90,
	0x1e, 0x14, 0x7f, 0x80, 0xcc, 0x1d, 0x06, 0x32, 0x34, 0x6c, 0xe2, 0x4d, 0xda, 0x25, 0x60, 0x60,
	0xb5, 0x35, 0xc9, 0x90, 0xfd, 0x0e, 0xff, 0x83, 0x17, 0x0f, 0xfe, 0x45, 0x49, 0xd2, 0x8e, 0xea,
	0x41, 0xf4, 0xa2, 0xde, 0xf2, 0xe5, 0x6d, 0xef, 0x7d, 0xef, 0xbd, 0xb6, 0x00, 0x2b, 0xc5, 0x65,
	0x52, 0xca, 0x42, 0x17, 0x38, 0x30, 0xe7, 0x32, 0x8b, 0xdf, 0x10, 0xf4, 0x46, 0x92, 0xa7, 0x9a,
	0xcf, 0x15, 0x97, 0x94, 0x3f, 0xae, 0xb8, 0xd2, 0xf8, 0x10, 0x3a, 0x26, 0x3e, 0x4d, 0x73, 0x4e,
	0x50, 0x1f, 0x0d, 0x76, 0xe8, 0x86, 0x4d, 0xac, 0x4c, 0x95, 0x7a, 0x2a, 0x24, 0x23, 0x2d, 0x17,
	0xab, 0x19, 0x1f, 0x40, 0x90, 0x17, 0x99, 0x58, 0x72, 0xe2, 0xd9, 0x48, 0x45, 0x38, 0x02, 0x9f,
	0xe7, 0xa9, 0x58, 0x92, 0xb6, 0xbd, 0x76, 0x60, 0x32, 0x65, 0x42, 0xea, 0x7b, 0x96, 0xae, 0x89,
	0xef, 0x32, 0xd5, 0x8c, 0x09, 0x6c, 0xa7, 0x8c, 0x49, 0xae, 0x14, 0x09, 0x6c, 0xa8, 0xc6, 0xf8,
	0x18, 0x70, 0x53, 0x58, 0x95, 0xc5, 0x83, 0xe2, 0xa6, 0xb2, 0x31, 0x9c, 0x30, 0xeb, 0xeb, 0xd1,
	0x8a, 0xe2, 0x67, 0x04, 0xbd, 0x79, 0xc9, 0x7e, 0xd0, 0xdf, 0x6f, 0xf4, 0x10, 0x01, 0x6e, 0x4a,
	0xb9, 0x1e, 0xe2, 0x04, 0xc2, 0xeb, 0x15, 0x97, 0xeb, 0x6f, 0x9a, 0xc6, 0xaf, 0x08, 0x7a, 0x8d,
	0x3f, 0x7c, 0x3d, 0x89, 0x0f, 0x99, 0x5a, 0x7f, 0xd0, 0xf3, 0x0b, 0x82, 0x5d, 0x23, 0x7a, 0x29,
	0x94, 0x9e, 0x68, 0x9e, 0xff, 0x5b, 0x51, 0x06, 0xd1, 0x66, 0xaa, 0x46, 0xb6, 0x5e, 0xc5, 0x11,
	0xc0, 0xc2, 0x3e, 0x78, 0x33, 0x51, 0x2d, 0xc3, 0xa3, 0x8d, 0x1b, 0xe3, 0xc6, 0x84, 0xe4, 0x0b,
	0x5d, 0x59, 0x57, 0x64, 0xdc, 0x96, 0x22, 0x17, 0xda, 0x2a, 0xfb, 0xd4, 0x41, 0x3c, 0x82, 0xfd,
	0x4f, 0x55, 0xaa, 0xfd, 0x0d, 0xc1, 0x37, 0xed, 0x2a, 0x82, 0xfa, 0xde, 0xa0, 0x7b, 0x12, 0x25,
	0xee, 0x4d, 0x4d, 0x9a, 0xb3, 0xa3, 0xee, 0x27, 0xc3, 0x33, 0xe8, 0xda, 0x24, 0x17, 0xae, 0x12,
	0x86, 0xbd, 0x06, 0xde, 0x4d, 0xcf, 0xc3, 0x2d, 0xdc, 0x81, 0xf6, 0x74, 0x7c, 0x3b, 0x0b, 0x91,
	0x39, 0x5d, 0xd1, 0xf1, 0x4d, 0xd8, 0xca, 0x02, 0xfb, 0x0d, 0x38, 0x7d, 0x0f, 0x00, 0x00, 0xff,
	0xff, 0xbf, 0xb5, 0x73, 0x1f, 0x11, 0x04, 0x00, 0x00,
}
